---
- name: Set up Ruby build environment (https://github.com/rbenv/ruby-build/wiki#suggested-build-environment)
  apt:
    name:
      - autoconf
      - bison
      - build-essential
      - libssl-dev
      - libyaml-dev
      - libreadline6-dev
      - zlib1g-dev
      - libncurses5-dev
      - libffi-dev
      - libgdbm6
      - libgdbm-dev
      - libdb-dev
  become: yes

- name: Clone rbenv repo
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv

- name: Compile dynamic bash extension to speed up rbenv
  command: src/configure && make -C src
  args:
    chdir: ~/.rbenv

- name: Clone ruby-build repo
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
